name: ArmorStand-Limiter
main: com.xSavior_of_God.ArmorStandLimiter.Main
version: maven-version-number
api-version: 1.13
folia-supported: true
author: xSavior_of_God
softdepend: [ModelEngine, HolographicDisplays]
commands:
  asl:
    description: reload the plugin
    usage:  /asl
            /asl reload
            /asl test
            /asl check <chunk/xyz>
permissions:
  armostandlimiter.reload:
    description: you can reload the plugin if you have this permission
    default: op
  armostandlimiter.check:
    description: you can check the number of ArmorStand in a chunk or block (default is block)
    default: op
  armostandlimiter.clear:
    description: you can clear the ArmorStand in a chunk or block (default is block)
    default: op
  armostandlimiter.test:
    description: you can test the notification system
    default: op
